# Generated by Django 3.0.5 on 2021-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOVIESinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year', models.DecimalField(decimal_places=0, max_digits=2025)),
                ('runtime_min', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('genres', models.TextField(blank=True, null=True)),
                ('language', models.TextField(default=True)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actors', models.TextField(default=True)),
            ],
        ),
    ]
