# Generated by Django 3.0.5 on 2021-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_moviesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='genres',
            field=models.TextField(default=True),
        ),
    ]
